# Generated by Django 5.1.4 on 2026-03-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='DateTimeField',
            new_name='created_at',
        ),
    ]
